name: Workflow Multi-jobs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Simuler une build
        run: echo "Compilation du projet..."

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Exécuter des tests
        run: echo "Tests en cours..."
