name: CI avec Secrets

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Utiliser un secret
        run: echo "Le secret est ${{ secrets.MY_SECRET }}"
